add docker compose gen

diff --git a/docker b/docker
--- a/docker
+++ b/docker
@@ -1,5 +1,4 @@
 #!/bin/sh
-
 set -e
 
 STATE="$1"
@@ -22,26 +21,27 @@ case "$STATE" in
         ;;
 
     ArtifactInstall)
-        >&2 echo "Storing reference on running containers for rollback needs to $prev_containers_file"
-        docker ps -q > $prev_containers_file
+        >&2 echo "Storing reference on running containers for rollback to $prev_containers_file"
+        docker ps -q > "$prev_containers_file"
 
-        >&2 echo "Stopping all running containers"
-        [ -n "$(cat $prev_containers_file)" ] && docker stop $(cat $prev_containers_file)
-        for container in $(jq -r ".containers[]" "$FILES"/header/meta-data); do
-            >&2 echo "Pulling new container [$container]"
-            docker pull $container
-            >&2 echo "Starting new container [$container]"
-            docker run -dt $container
-        done
+        >&2 echo "Running docker compose"
+        docker compose --file "$FILES"/files/docker-compose.yml --remove-orphans --project-name calllogger
         ;;
 
     ArtifactRollback)
-        >&2 echo "Container update rollback started"
-        [ -f $prev_containers_file ] ||  (>&2 echo "ERROR: Failed to find rollback reference file [$prev_containers_file]" && exit 1)
+        >&2 echo "Container rollback started"
+        [ -f "$prev_containers_file" ] ||  (>&2 echo "ERROR: Failed to find rollback reference file [$prev_containers_file]" && exit 1)
+
         >&2 echo "Stopping all running containers"
-        [ -n  "$(docker ps -q)" ] && docker stop $(docker ps -q)
+        [ -n  "$(docker ps -q)" ] && docker stop "$(docker ps -q)"
+
         >&2 echo "Starting containers running prior to the update"
         [ -n "$(cat $prev_containers_file)" ] && docker start $(cat $prev_containers_file)
+        ;;
+
+    ArtifactCommit)
+        >&2 echo "Running docker cleanup"
+        docker system prune --force
         ;;
 esac
 
